server:
  port: 80
zuul:
  routes:
    actors:
      path: /actors-management/**
      serviceId: actors-service
    films:
      path: /films-management/**
      serviceId: films-service

spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url.default: http://localhost:8761/eureka
